### ISSUE TITLE
Errors compiling otm-sim using `mvn install -DskipTests`

### ISSUE THREAD

**Issue by temetski** [ggomes/otm-sim#6]
I am unable to run otm-sim on a fresh install, compiled from branch feb9e9f3651deebf031d28f9d21468552558d206. I'm getting this error:

```
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
        jaxb.Scenario cannot be resolved to a type

        at api.API.load(API.java:63)
        at runner.OTM.load(OTM.java:163)
        at runner.OTM.main(OTM.java:111)
```

Inspecting the code further, it seems that there are missing references to objects under the jaxb namespace.

**Comment by temetski** [comment]
Purging the m2 repository via `rm -rf ~/.m2/repository/otm`, and doing another fresh clone of otm-sim seemed to do the trick.
